### ISSUE TITLE
Status of the repository?

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/darwin-stubs#12]
Hi,

As part of https://github.com/NixOS/teams-collaboration/issues/1, I am trying to clarify the status of the repositories under the NixOS organisation.

This repository seems to be unmaintained or obsolete, so it will be archived in a month.

If you think it warrants staying here or should be moved to another organization instead, please answer this issue.

**Comment by thefloweringash** [comment]
Hello,

Thanks for keeping things tidy!

This repository is a description of the binary libraries provided by macOS 10.12. It's used by nixpkgs as the source of the [darwin.darwin-stubs](https://github.com/NixOS/nixpkgs/blob/139f39716f8d6c3655714669dd26ea821a88df82/pkgs/os-specific/darwin/darwin-stubs/default.nix#L8) package, which is used to provide the interfaces when linking against the [darwin frameworks in `darwin.apple_sdk.frameworks.*`](https://github.com/NixOS/nixpkgs/blob/139f39716f8d6c3655714669dd26ea821a88df82/pkgs/os-specific/darwin/apple-sdk/default.nix#L100) (and a few other places).

Admittedly there haven't been many changes to the repository, and it may be unmaintained for all practical purposes, but so long as nixpkgs relies on this, it seems prudent to keep the repository unarchived.

**Comment by reckenrode** [comment]
I wouldn’t expect this repository to change except when new, source-based SDK versions are added to nixpkgs (unless/until we use the stubs provided upstream).

**Comment by thufschmitt** [comment]
Thanks,

I had been told that maybe this wasn't used by Nixpkgs any more after some refactoring. But if it's still used, we certainly should keep it!
